// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/joseMarciano/crypto-manager/internal/app/user/domain"

	mock "github.com/stretchr/testify/mock"
)

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

type Creator_Expecter struct {
	mock *mock.Mock
}

func (_m *Creator) EXPECT() *Creator_Expecter {
	return &Creator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *Creator) Create(_a0 context.Context, _a1 domain.User) (domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Creator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Creator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.User
func (_e *Creator_Expecter) Create(_a0 interface{}, _a1 interface{}) *Creator_Create_Call {
	return &Creator_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *Creator_Create_Call) Run(run func(_a0 context.Context, _a1 domain.User)) *Creator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *Creator_Create_Call) Return(_a0 domain.User, _a1 error) *Creator_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Creator_Create_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *Creator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator {
	mock := &Creator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
