// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

type Finder_Expecter struct {
	mock *mock.Mock
}

func (_m *Finder) EXPECT() *Finder_Expecter {
	return &Finder_Expecter{mock: &_m.Mock}
}

// ExistsByDocument provides a mock function with given fields: _a0, _a1
func (_m *Finder) ExistsByDocument(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByDocument")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finder_ExistsByDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByDocument'
type Finder_ExistsByDocument_Call struct {
	*mock.Call
}

// ExistsByDocument is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *Finder_Expecter) ExistsByDocument(_a0 interface{}, _a1 interface{}) *Finder_ExistsByDocument_Call {
	return &Finder_ExistsByDocument_Call{Call: _e.mock.On("ExistsByDocument", _a0, _a1)}
}

func (_c *Finder_ExistsByDocument_Call) Run(run func(_a0 context.Context, _a1 string)) *Finder_ExistsByDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Finder_ExistsByDocument_Call) Return(_a0 bool, _a1 error) *Finder_ExistsByDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Finder_ExistsByDocument_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Finder_ExistsByDocument_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function with given fields: _a0, _a1
func (_m *Finder) ExistsByName(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finder_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type Finder_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *Finder_Expecter) ExistsByName(_a0 interface{}, _a1 interface{}) *Finder_ExistsByName_Call {
	return &Finder_ExistsByName_Call{Call: _e.mock.On("ExistsByName", _a0, _a1)}
}

func (_c *Finder_ExistsByName_Call) Run(run func(_a0 context.Context, _a1 string)) *Finder_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Finder_ExistsByName_Call) Return(_a0 bool, _a1 error) *Finder_ExistsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Finder_ExistsByName_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Finder_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinder creates a new instance of Finder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Finder {
	mock := &Finder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
