// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/exchange/withdraw/withdraw.proto

package withdraw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    string                 `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_proto_exchange_withdraw_withdraw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_withdraw_withdraw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_withdraw_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *WithdrawRequest) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

func (x *WithdrawRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WithdrawRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_proto_exchange_withdraw_withdraw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_withdraw_withdraw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_withdraw_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WithdrawResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_exchange_withdraw_withdraw_proto protoreflect.FileDescriptor

const file_proto_exchange_withdraw_withdraw_proto_rawDesc = "" +
	"\n" +
	"&proto/exchange/withdraw/withdraw.proto\"i\n" +
	"\x0fWithdrawRequest\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\tR\n" +
	"exchangeId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"K\n" +
	"\x10WithdrawResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2A\n" +
	"\x0fWithdrawHandler\x12.\n" +
	"\aExecute\x12\x10.WithdrawRequest\x1a\x11.WithdrawResponseB1Z/github.com/joseMarciano/crypto-manager/withdrawb\x06proto3"

var (
	file_proto_exchange_withdraw_withdraw_proto_rawDescOnce sync.Once
	file_proto_exchange_withdraw_withdraw_proto_rawDescData []byte
)

func file_proto_exchange_withdraw_withdraw_proto_rawDescGZIP() []byte {
	file_proto_exchange_withdraw_withdraw_proto_rawDescOnce.Do(func() {
		file_proto_exchange_withdraw_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_withdraw_withdraw_proto_rawDesc), len(file_proto_exchange_withdraw_withdraw_proto_rawDesc)))
	})
	return file_proto_exchange_withdraw_withdraw_proto_rawDescData
}

var file_proto_exchange_withdraw_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_withdraw_withdraw_proto_goTypes = []any{
	(*WithdrawRequest)(nil),  // 0: WithdrawRequest
	(*WithdrawResponse)(nil), // 1: WithdrawResponse
}
var file_proto_exchange_withdraw_withdraw_proto_depIdxs = []int32{
	0, // 0: WithdrawHandler.Execute:input_type -> WithdrawRequest
	1, // 1: WithdrawHandler.Execute:output_type -> WithdrawResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_withdraw_withdraw_proto_init() }
func file_proto_exchange_withdraw_withdraw_proto_init() {
	if File_proto_exchange_withdraw_withdraw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_withdraw_withdraw_proto_rawDesc), len(file_proto_exchange_withdraw_withdraw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_withdraw_withdraw_proto_goTypes,
		DependencyIndexes: file_proto_exchange_withdraw_withdraw_proto_depIdxs,
		MessageInfos:      file_proto_exchange_withdraw_withdraw_proto_msgTypes,
	}.Build()
	File_proto_exchange_withdraw_withdraw_proto = out.File
	file_proto_exchange_withdraw_withdraw_proto_goTypes = nil
	file_proto_exchange_withdraw_withdraw_proto_depIdxs = nil
}
