// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/exchange/withdraw/withdraw.proto

package withdraw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WithdrawHandler_Execute_FullMethodName = "/WithdrawHandler/Execute"
)

// WithdrawHandlerClient is the client API for WithdrawHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawHandlerClient interface {
	Execute(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
}

type withdrawHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawHandlerClient(cc grpc.ClientConnInterface) WithdrawHandlerClient {
	return &withdrawHandlerClient{cc}
}

func (c *withdrawHandlerClient) Execute(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, WithdrawHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawHandlerServer is the server API for WithdrawHandler service.
// All implementations must embed UnimplementedWithdrawHandlerServer
// for forward compatibility.
type WithdrawHandlerServer interface {
	Execute(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	mustEmbedUnimplementedWithdrawHandlerServer()
}

// UnimplementedWithdrawHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWithdrawHandlerServer struct{}

func (UnimplementedWithdrawHandlerServer) Execute(context.Context, *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWithdrawHandlerServer) mustEmbedUnimplementedWithdrawHandlerServer() {}
func (UnimplementedWithdrawHandlerServer) testEmbeddedByValue()                         {}

// UnsafeWithdrawHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawHandlerServer will
// result in compilation errors.
type UnsafeWithdrawHandlerServer interface {
	mustEmbedUnimplementedWithdrawHandlerServer()
}

func RegisterWithdrawHandlerServer(s grpc.ServiceRegistrar, srv WithdrawHandlerServer) {
	// If the following call pancis, it indicates UnimplementedWithdrawHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WithdrawHandler_ServiceDesc, srv)
}

func _WithdrawHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawHandlerServer).Execute(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WithdrawHandler_ServiceDesc is the grpc.ServiceDesc for WithdrawHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithdrawHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WithdrawHandler",
	HandlerType: (*WithdrawHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _WithdrawHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exchange/withdraw/withdraw.proto",
}
