// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/exchange/createaccount/account.proto

package createaccount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateAccountHandler_Execute_FullMethodName = "/CreateAccountHandler/Execute"
)

// CreateAccountHandlerClient is the client API for CreateAccountHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateAccountHandlerClient interface {
	Execute(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type createAccountHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateAccountHandlerClient(cc grpc.ClientConnInterface) CreateAccountHandlerClient {
	return &createAccountHandlerClient{cc}
}

func (c *createAccountHandlerClient) Execute(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, CreateAccountHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateAccountHandlerServer is the server API for CreateAccountHandler service.
// All implementations must embed UnimplementedCreateAccountHandlerServer
// for forward compatibility.
type CreateAccountHandlerServer interface {
	Execute(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	mustEmbedUnimplementedCreateAccountHandlerServer()
}

// UnimplementedCreateAccountHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateAccountHandlerServer struct{}

func (UnimplementedCreateAccountHandlerServer) Execute(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCreateAccountHandlerServer) mustEmbedUnimplementedCreateAccountHandlerServer() {}
func (UnimplementedCreateAccountHandlerServer) testEmbeddedByValue()                              {}

// UnsafeCreateAccountHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateAccountHandlerServer will
// result in compilation errors.
type UnsafeCreateAccountHandlerServer interface {
	mustEmbedUnimplementedCreateAccountHandlerServer()
}

func RegisterCreateAccountHandlerServer(s grpc.ServiceRegistrar, srv CreateAccountHandlerServer) {
	// If the following call pancis, it indicates UnimplementedCreateAccountHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateAccountHandler_ServiceDesc, srv)
}

func _CreateAccountHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateAccountHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateAccountHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateAccountHandlerServer).Execute(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateAccountHandler_ServiceDesc is the grpc.ServiceDesc for CreateAccountHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateAccountHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CreateAccountHandler",
	HandlerType: (*CreateAccountHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _CreateAccountHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exchange/createaccount/account.proto",
}
