// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/exchange/createaccount/account.proto

package createaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExchangeId    string                 `protobuf:"bytes,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_exchange_createaccount_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_createaccount_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_createaccount_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExchangeId    string                 `protobuf:"bytes,3,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_exchange_createaccount_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_createaccount_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_createaccount_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountResponse) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

func (x *CreateAccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_exchange_createaccount_account_proto protoreflect.FileDescriptor

const file_proto_exchange_createaccount_account_proto_rawDesc = "" +
	"\n" +
	"*proto/exchange/createaccount/account.proto\"P\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vexchange_id\x18\x02 \x01(\tR\n" +
	"exchangeId\"{\n" +
	"\x15CreateAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vexchange_id\x18\x03 \x01(\tR\n" +
	"exchangeId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance2P\n" +
	"\x14CreateAccountHandler\x128\n" +
	"\aExecute\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponseB6Z4github.com/joseMarciano/crypto-manager/createaccountb\x06proto3"

var (
	file_proto_exchange_createaccount_account_proto_rawDescOnce sync.Once
	file_proto_exchange_createaccount_account_proto_rawDescData []byte
)

func file_proto_exchange_createaccount_account_proto_rawDescGZIP() []byte {
	file_proto_exchange_createaccount_account_proto_rawDescOnce.Do(func() {
		file_proto_exchange_createaccount_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_createaccount_account_proto_rawDesc), len(file_proto_exchange_createaccount_account_proto_rawDesc)))
	})
	return file_proto_exchange_createaccount_account_proto_rawDescData
}

var file_proto_exchange_createaccount_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_createaccount_account_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: CreateAccountResponse
}
var file_proto_exchange_createaccount_account_proto_depIdxs = []int32{
	0, // 0: CreateAccountHandler.Execute:input_type -> CreateAccountRequest
	1, // 1: CreateAccountHandler.Execute:output_type -> CreateAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_createaccount_account_proto_init() }
func file_proto_exchange_createaccount_account_proto_init() {
	if File_proto_exchange_createaccount_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_createaccount_account_proto_rawDesc), len(file_proto_exchange_createaccount_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_createaccount_account_proto_goTypes,
		DependencyIndexes: file_proto_exchange_createaccount_account_proto_depIdxs,
		MessageInfos:      file_proto_exchange_createaccount_account_proto_msgTypes,
	}.Build()
	File_proto_exchange_createaccount_account_proto = out.File
	file_proto_exchange_createaccount_account_proto_goTypes = nil
	file_proto_exchange_createaccount_account_proto_depIdxs = nil
}
