CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    DOCUMENT_NUMBER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS EXCHANGES (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    MINIMUM_AGE INTEGER NOT NULL,
    MAXIMUM_TRANSFER_AMOUNT DECIMAL(15,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL,
    EXCHANGE_ID UUID NOT NULL,
    BALANCE DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGES(ID)
);

CREATE TABLE IF NOT EXISTS EXCHANGE_TRANSACTIONS (
    ID UUID PRIMARY KEY,
    EXCHANGE_ID UUID NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    EXECUTED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGES(ID)
);

CREATE OR REPLACE VIEW EXCHANGE_TRANSACTIONS_VIEW AS
    SELECT ET.EXCHANGE_ID, ET.EXECUTED_AT::DATE, ET.TYPE,SUM(ET.AMOUNT) AS AMOUNT
    FROM EXCHANGE_TRANSACTIONS ET
    GROUP BY ET.EXCHANGE_ID, ET.EXECUTED_AT::DATE, ET.TYPE;