// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/report/balance/balance.proto

package balance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceHandler_Execute_FullMethodName = "/BalanceHandler/Execute"
)

// BalanceHandlerClient is the client API for BalanceHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceHandlerClient interface {
	Execute(ctx context.Context, in *FetchBalanceRequest, opts ...grpc.CallOption) (*FetchBalanceResponse, error)
}

type balanceHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceHandlerClient(cc grpc.ClientConnInterface) BalanceHandlerClient {
	return &balanceHandlerClient{cc}
}

func (c *balanceHandlerClient) Execute(ctx context.Context, in *FetchBalanceRequest, opts ...grpc.CallOption) (*FetchBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchBalanceResponse)
	err := c.cc.Invoke(ctx, BalanceHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceHandlerServer is the server API for BalanceHandler service.
// All implementations must embed UnimplementedBalanceHandlerServer
// for forward compatibility.
type BalanceHandlerServer interface {
	Execute(context.Context, *FetchBalanceRequest) (*FetchBalanceResponse, error)
	mustEmbedUnimplementedBalanceHandlerServer()
}

// UnimplementedBalanceHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceHandlerServer struct{}

func (UnimplementedBalanceHandlerServer) Execute(context.Context, *FetchBalanceRequest) (*FetchBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedBalanceHandlerServer) mustEmbedUnimplementedBalanceHandlerServer() {}
func (UnimplementedBalanceHandlerServer) testEmbeddedByValue()                        {}

// UnsafeBalanceHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceHandlerServer will
// result in compilation errors.
type UnsafeBalanceHandlerServer interface {
	mustEmbedUnimplementedBalanceHandlerServer()
}

func RegisterBalanceHandlerServer(s grpc.ServiceRegistrar, srv BalanceHandlerServer) {
	// If the following call pancis, it indicates UnimplementedBalanceHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceHandler_ServiceDesc, srv)
}

func _BalanceHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceHandlerServer).Execute(ctx, req.(*FetchBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceHandler_ServiceDesc is the grpc.ServiceDesc for BalanceHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BalanceHandler",
	HandlerType: (*BalanceHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _BalanceHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/report/balance/balance.proto",
}
