// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/report/balance/balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBalanceRequest) Reset() {
	*x = FetchBalanceRequest{}
	mi := &file_proto_report_balance_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBalanceRequest) ProtoMessage() {}

func (x *FetchBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_balance_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBalanceRequest.ProtoReflect.Descriptor instead.
func (*FetchBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_report_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *FetchBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    string                 `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_proto_report_balance_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_balance_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_proto_report_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *Balance) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

func (x *Balance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type FetchBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Balances      []*Balance             `protobuf:"bytes,3,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBalanceResponse) Reset() {
	*x = FetchBalanceResponse{}
	mi := &file_proto_report_balance_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBalanceResponse) ProtoMessage() {}

func (x *FetchBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_balance_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBalanceResponse.ProtoReflect.Descriptor instead.
func (*FetchBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_report_balance_balance_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchBalanceResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *FetchBalanceResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

var File_proto_report_balance_balance_proto protoreflect.FileDescriptor

const file_proto_report_balance_balance_proto_rawDesc = "" +
	"\n" +
	"\"proto/report/balance/balance.proto\".\n" +
	"\x13FetchBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\aBalance\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\tR\n" +
	"exchangeId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"z\n" +
	"\x14FetchBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x01R\ftotalBalance\x12$\n" +
	"\bbalances\x18\x03 \x03(\v2\b.BalanceR\bbalances2H\n" +
	"\x0eBalanceHandler\x126\n" +
	"\aExecute\x12\x14.FetchBalanceRequest\x1a\x15.FetchBalanceResponseB0Z.github.com/joseMarciano/crypto-manager/balanceb\x06proto3"

var (
	file_proto_report_balance_balance_proto_rawDescOnce sync.Once
	file_proto_report_balance_balance_proto_rawDescData []byte
)

func file_proto_report_balance_balance_proto_rawDescGZIP() []byte {
	file_proto_report_balance_balance_proto_rawDescOnce.Do(func() {
		file_proto_report_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_report_balance_balance_proto_rawDesc), len(file_proto_report_balance_balance_proto_rawDesc)))
	})
	return file_proto_report_balance_balance_proto_rawDescData
}

var file_proto_report_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_report_balance_balance_proto_goTypes = []any{
	(*FetchBalanceRequest)(nil),  // 0: FetchBalanceRequest
	(*Balance)(nil),              // 1: Balance
	(*FetchBalanceResponse)(nil), // 2: FetchBalanceResponse
}
var file_proto_report_balance_balance_proto_depIdxs = []int32{
	1, // 0: FetchBalanceResponse.balances:type_name -> Balance
	0, // 1: BalanceHandler.Execute:input_type -> FetchBalanceRequest
	2, // 2: BalanceHandler.Execute:output_type -> FetchBalanceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_report_balance_balance_proto_init() }
func file_proto_report_balance_balance_proto_init() {
	if File_proto_report_balance_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_report_balance_balance_proto_rawDesc), len(file_proto_report_balance_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_report_balance_balance_proto_goTypes,
		DependencyIndexes: file_proto_report_balance_balance_proto_depIdxs,
		MessageInfos:      file_proto_report_balance_balance_proto_msgTypes,
	}.Build()
	File_proto_report_balance_balance_proto = out.File
	file_proto_report_balance_balance_proto_goTypes = nil
	file_proto_report_balance_balance_proto_depIdxs = nil
}
