// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/report/exchangetransaction/exchangetransaction.proto

package exchangetransaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeTransactionHandler_Execute_FullMethodName = "/ExchangeTransactionHandler/Execute"
)

// ExchangeTransactionHandlerClient is the client API for ExchangeTransactionHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeTransactionHandlerClient interface {
	Execute(ctx context.Context, in *FetchExchangeTransactionRequest, opts ...grpc.CallOption) (*FetchExchangeTransactionResponse, error)
}

type exchangeTransactionHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeTransactionHandlerClient(cc grpc.ClientConnInterface) ExchangeTransactionHandlerClient {
	return &exchangeTransactionHandlerClient{cc}
}

func (c *exchangeTransactionHandlerClient) Execute(ctx context.Context, in *FetchExchangeTransactionRequest, opts ...grpc.CallOption) (*FetchExchangeTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchExchangeTransactionResponse)
	err := c.cc.Invoke(ctx, ExchangeTransactionHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeTransactionHandlerServer is the server API for ExchangeTransactionHandler service.
// All implementations must embed UnimplementedExchangeTransactionHandlerServer
// for forward compatibility.
type ExchangeTransactionHandlerServer interface {
	Execute(context.Context, *FetchExchangeTransactionRequest) (*FetchExchangeTransactionResponse, error)
	mustEmbedUnimplementedExchangeTransactionHandlerServer()
}

// UnimplementedExchangeTransactionHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeTransactionHandlerServer struct{}

func (UnimplementedExchangeTransactionHandlerServer) Execute(context.Context, *FetchExchangeTransactionRequest) (*FetchExchangeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedExchangeTransactionHandlerServer) mustEmbedUnimplementedExchangeTransactionHandlerServer() {
}
func (UnimplementedExchangeTransactionHandlerServer) testEmbeddedByValue() {}

// UnsafeExchangeTransactionHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeTransactionHandlerServer will
// result in compilation errors.
type UnsafeExchangeTransactionHandlerServer interface {
	mustEmbedUnimplementedExchangeTransactionHandlerServer()
}

func RegisterExchangeTransactionHandlerServer(s grpc.ServiceRegistrar, srv ExchangeTransactionHandlerServer) {
	// If the following call pancis, it indicates UnimplementedExchangeTransactionHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeTransactionHandler_ServiceDesc, srv)
}

func _ExchangeTransactionHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchExchangeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeTransactionHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeTransactionHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeTransactionHandlerServer).Execute(ctx, req.(*FetchExchangeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeTransactionHandler_ServiceDesc is the grpc.ServiceDesc for ExchangeTransactionHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeTransactionHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExchangeTransactionHandler",
	HandlerType: (*ExchangeTransactionHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ExchangeTransactionHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/report/exchangetransaction/exchangetransaction.proto",
}
