// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/report/exchangetransaction/exchangetransaction.proto

package exchangetransaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchExchangeTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExchangeTransactionRequest) Reset() {
	*x = FetchExchangeTransactionRequest{}
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExchangeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExchangeTransactionRequest) ProtoMessage() {}

func (x *FetchExchangeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExchangeTransactionRequest.ProtoReflect.Descriptor instead.
func (*FetchExchangeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP(), []int{0}
}

func (x *FetchExchangeTransactionRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FetchExchangeTransactionRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type Total struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Total) Reset() {
	*x = Total{}
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Total) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Total) ProtoMessage() {}

func (x *Total) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Total.ProtoReflect.Descriptor instead.
func (*Total) Descriptor() ([]byte, []int) {
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP(), []int{1}
}

func (x *Total) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Total) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Totals        []*Total               `protobuf:"bytes,2,rep,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP(), []int{2}
}

func (x *Date) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Date) GetTotals() []*Total {
	if x != nil {
		return x.Totals
	}
	return nil
}

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    string                 `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Dates         []*Date                `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP(), []int{3}
}

func (x *Exchange) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

func (x *Exchange) GetDates() []*Date {
	if x != nil {
		return x.Dates
	}
	return nil
}

type FetchExchangeTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Exchange            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExchangeTransactionResponse) Reset() {
	*x = FetchExchangeTransactionResponse{}
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExchangeTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExchangeTransactionResponse) ProtoMessage() {}

func (x *FetchExchangeTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExchangeTransactionResponse.ProtoReflect.Descriptor instead.
func (*FetchExchangeTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP(), []int{4}
}

func (x *FetchExchangeTransactionResponse) GetData() []*Exchange {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_report_exchangetransaction_exchangetransaction_proto protoreflect.FileDescriptor

const file_proto_report_exchangetransaction_exchangetransaction_proto_rawDesc = "" +
	"\n" +
	":proto/report/exchangetransaction/exchangetransaction.proto\"[\n" +
	"\x1fFetchExchangeTransactionRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"3\n" +
	"\x05Total\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\":\n" +
	"\x04Date\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1e\n" +
	"\x06totals\x18\x02 \x03(\v2\x06.TotalR\x06totals\"H\n" +
	"\bExchange\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\tR\n" +
	"exchangeId\x12\x1b\n" +
	"\x05dates\x18\x02 \x03(\v2\x05.DateR\x05dates\"A\n" +
	" FetchExchangeTransactionResponse\x12\x1d\n" +
	"\x04data\x18\x01 \x03(\v2\t.ExchangeR\x04data2l\n" +
	"\x1aExchangeTransactionHandler\x12N\n" +
	"\aExecute\x12 .FetchExchangeTransactionRequest\x1a!.FetchExchangeTransactionResponseB<Z:github.com/joseMarciano/crypto-manager/exchangetransactionb\x06proto3"

var (
	file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescOnce sync.Once
	file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescData []byte
)

func file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescGZIP() []byte {
	file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescOnce.Do(func() {
		file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_report_exchangetransaction_exchangetransaction_proto_rawDesc), len(file_proto_report_exchangetransaction_exchangetransaction_proto_rawDesc)))
	})
	return file_proto_report_exchangetransaction_exchangetransaction_proto_rawDescData
}

var file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_report_exchangetransaction_exchangetransaction_proto_goTypes = []any{
	(*FetchExchangeTransactionRequest)(nil),  // 0: FetchExchangeTransactionRequest
	(*Total)(nil),                            // 1: Total
	(*Date)(nil),                             // 2: Date
	(*Exchange)(nil),                         // 3: Exchange
	(*FetchExchangeTransactionResponse)(nil), // 4: FetchExchangeTransactionResponse
}
var file_proto_report_exchangetransaction_exchangetransaction_proto_depIdxs = []int32{
	1, // 0: Date.totals:type_name -> Total
	2, // 1: Exchange.dates:type_name -> Date
	3, // 2: FetchExchangeTransactionResponse.data:type_name -> Exchange
	0, // 3: ExchangeTransactionHandler.Execute:input_type -> FetchExchangeTransactionRequest
	4, // 4: ExchangeTransactionHandler.Execute:output_type -> FetchExchangeTransactionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_report_exchangetransaction_exchangetransaction_proto_init() }
func file_proto_report_exchangetransaction_exchangetransaction_proto_init() {
	if File_proto_report_exchangetransaction_exchangetransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_report_exchangetransaction_exchangetransaction_proto_rawDesc), len(file_proto_report_exchangetransaction_exchangetransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_report_exchangetransaction_exchangetransaction_proto_goTypes,
		DependencyIndexes: file_proto_report_exchangetransaction_exchangetransaction_proto_depIdxs,
		MessageInfos:      file_proto_report_exchangetransaction_exchangetransaction_proto_msgTypes,
	}.Build()
	File_proto_report_exchangetransaction_exchangetransaction_proto = out.File
	file_proto_report_exchangetransaction_exchangetransaction_proto_goTypes = nil
	file_proto_report_exchangetransaction_exchangetransaction_proto_depIdxs = nil
}
