// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/user/create/user.proto

package createuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateUserHandler_Execute_FullMethodName = "/CreateUserHandler/Execute"
)

// CreateUserHandlerClient is the client API for CreateUserHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateUserHandlerClient interface {
	Execute(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type createUserHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateUserHandlerClient(cc grpc.ClientConnInterface) CreateUserHandlerClient {
	return &createUserHandlerClient{cc}
}

func (c *createUserHandlerClient) Execute(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, CreateUserHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateUserHandlerServer is the server API for CreateUserHandler service.
// All implementations must embed UnimplementedCreateUserHandlerServer
// for forward compatibility.
type CreateUserHandlerServer interface {
	Execute(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedCreateUserHandlerServer()
}

// UnimplementedCreateUserHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateUserHandlerServer struct{}

func (UnimplementedCreateUserHandlerServer) Execute(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCreateUserHandlerServer) mustEmbedUnimplementedCreateUserHandlerServer() {}
func (UnimplementedCreateUserHandlerServer) testEmbeddedByValue()                           {}

// UnsafeCreateUserHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateUserHandlerServer will
// result in compilation errors.
type UnsafeCreateUserHandlerServer interface {
	mustEmbedUnimplementedCreateUserHandlerServer()
}

func RegisterCreateUserHandlerServer(s grpc.ServiceRegistrar, srv CreateUserHandlerServer) {
	// If the following call pancis, it indicates UnimplementedCreateUserHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateUserHandler_ServiceDesc, srv)
}

func _CreateUserHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateUserHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateUserHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateUserHandlerServer).Execute(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateUserHandler_ServiceDesc is the grpc.ServiceDesc for CreateUserHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateUserHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CreateUserHandler",
	HandlerType: (*CreateUserHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _CreateUserHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/create/user.proto",
}
