// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/exchange/create/exchange.proto

package createexchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExchangeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinimumAge            int32                  `protobuf:"zigzag32,2,opt,name=minimum_age,json=minimumAge,proto3" json:"minimum_age,omitempty"`
	MaximumTransferAmount float64                `protobuf:"fixed64,3,opt,name=maximum_transfer_amount,json=maximumTransferAmount,proto3" json:"maximum_transfer_amount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateExchangeRequest) Reset() {
	*x = CreateExchangeRequest{}
	mi := &file_proto_exchange_create_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRequest) ProtoMessage() {}

func (x *CreateExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_create_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRequest.ProtoReflect.Descriptor instead.
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_create_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExchangeRequest) GetMinimumAge() int32 {
	if x != nil {
		return x.MinimumAge
	}
	return 0
}

func (x *CreateExchangeRequest) GetMaximumTransferAmount() float64 {
	if x != nil {
		return x.MaximumTransferAmount
	}
	return 0
}

type CreateExchangeResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinimumAge            uint32                 `protobuf:"varint,3,opt,name=minimum_age,json=minimumAge,proto3" json:"minimum_age,omitempty"`
	MaximumTransferAmount float64                `protobuf:"fixed64,4,opt,name=maximum_transfer_amount,json=maximumTransferAmount,proto3" json:"maximum_transfer_amount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateExchangeResponse) Reset() {
	*x = CreateExchangeResponse{}
	mi := &file_proto_exchange_create_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeResponse) ProtoMessage() {}

func (x *CreateExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_create_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeResponse.ProtoReflect.Descriptor instead.
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_create_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExchangeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateExchangeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExchangeResponse) GetMinimumAge() uint32 {
	if x != nil {
		return x.MinimumAge
	}
	return 0
}

func (x *CreateExchangeResponse) GetMaximumTransferAmount() float64 {
	if x != nil {
		return x.MaximumTransferAmount
	}
	return 0
}

var File_proto_exchange_create_exchange_proto protoreflect.FileDescriptor

const file_proto_exchange_create_exchange_proto_rawDesc = "" +
	"\n" +
	"$proto/exchange/create/exchange.proto\"\x84\x01\n" +
	"\x15CreateExchangeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vminimum_age\x18\x02 \x01(\x11R\n" +
	"minimumAge\x126\n" +
	"\x17maximum_transfer_amount\x18\x03 \x01(\x01R\x15maximumTransferAmount\"\x95\x01\n" +
	"\x16CreateExchangeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vminimum_age\x18\x03 \x01(\rR\n" +
	"minimumAge\x126\n" +
	"\x17maximum_transfer_amount\x18\x04 \x01(\x01R\x15maximumTransferAmount2S\n" +
	"\x15CreateExchangeHandler\x12:\n" +
	"\aExecute\x12\x16.CreateExchangeRequest\x1a\x17.CreateExchangeResponseB7Z5github.com/joseMarciano/crypto-manager/createexchangeb\x06proto3"

var (
	file_proto_exchange_create_exchange_proto_rawDescOnce sync.Once
	file_proto_exchange_create_exchange_proto_rawDescData []byte
)

func file_proto_exchange_create_exchange_proto_rawDescGZIP() []byte {
	file_proto_exchange_create_exchange_proto_rawDescOnce.Do(func() {
		file_proto_exchange_create_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_create_exchange_proto_rawDesc), len(file_proto_exchange_create_exchange_proto_rawDesc)))
	})
	return file_proto_exchange_create_exchange_proto_rawDescData
}

var file_proto_exchange_create_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_create_exchange_proto_goTypes = []any{
	(*CreateExchangeRequest)(nil),  // 0: CreateExchangeRequest
	(*CreateExchangeResponse)(nil), // 1: CreateExchangeResponse
}
var file_proto_exchange_create_exchange_proto_depIdxs = []int32{
	0, // 0: CreateExchangeHandler.Execute:input_type -> CreateExchangeRequest
	1, // 1: CreateExchangeHandler.Execute:output_type -> CreateExchangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_create_exchange_proto_init() }
func file_proto_exchange_create_exchange_proto_init() {
	if File_proto_exchange_create_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_create_exchange_proto_rawDesc), len(file_proto_exchange_create_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_create_exchange_proto_goTypes,
		DependencyIndexes: file_proto_exchange_create_exchange_proto_depIdxs,
		MessageInfos:      file_proto_exchange_create_exchange_proto_msgTypes,
	}.Build()
	File_proto_exchange_create_exchange_proto = out.File
	file_proto_exchange_create_exchange_proto_goTypes = nil
	file_proto_exchange_create_exchange_proto_depIdxs = nil
}
