// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/exchange/create/exchange.proto

package createexchange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateExchangeHandler_Execute_FullMethodName = "/CreateExchangeHandler/Execute"
)

// CreateExchangeHandlerClient is the client API for CreateExchangeHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateExchangeHandlerClient interface {
	Execute(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
}

type createExchangeHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateExchangeHandlerClient(cc grpc.ClientConnInterface) CreateExchangeHandlerClient {
	return &createExchangeHandlerClient{cc}
}

func (c *createExchangeHandlerClient) Execute(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, CreateExchangeHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateExchangeHandlerServer is the server API for CreateExchangeHandler service.
// All implementations must embed UnimplementedCreateExchangeHandlerServer
// for forward compatibility.
type CreateExchangeHandlerServer interface {
	Execute(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	mustEmbedUnimplementedCreateExchangeHandlerServer()
}

// UnimplementedCreateExchangeHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateExchangeHandlerServer struct{}

func (UnimplementedCreateExchangeHandlerServer) Execute(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCreateExchangeHandlerServer) mustEmbedUnimplementedCreateExchangeHandlerServer() {}
func (UnimplementedCreateExchangeHandlerServer) testEmbeddedByValue()                               {}

// UnsafeCreateExchangeHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateExchangeHandlerServer will
// result in compilation errors.
type UnsafeCreateExchangeHandlerServer interface {
	mustEmbedUnimplementedCreateExchangeHandlerServer()
}

func RegisterCreateExchangeHandlerServer(s grpc.ServiceRegistrar, srv CreateExchangeHandlerServer) {
	// If the following call pancis, it indicates UnimplementedCreateExchangeHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateExchangeHandler_ServiceDesc, srv)
}

func _CreateExchangeHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateExchangeHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateExchangeHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateExchangeHandlerServer).Execute(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateExchangeHandler_ServiceDesc is the grpc.ServiceDesc for CreateExchangeHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateExchangeHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CreateExchangeHandler",
	HandlerType: (*CreateExchangeHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _CreateExchangeHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exchange/create/exchange.proto",
}
