// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/exchange/deposit/deposit.proto

package deposit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepositHandler_Execute_FullMethodName = "/DepositHandler/Execute"
)

// DepositHandlerClient is the client API for DepositHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepositHandlerClient interface {
	Execute(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
}

type depositHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositHandlerClient(cc grpc.ClientConnInterface) DepositHandlerClient {
	return &depositHandlerClient{cc}
}

func (c *depositHandlerClient) Execute(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, DepositHandler_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositHandlerServer is the server API for DepositHandler service.
// All implementations must embed UnimplementedDepositHandlerServer
// for forward compatibility.
type DepositHandlerServer interface {
	Execute(context.Context, *DepositRequest) (*DepositResponse, error)
	mustEmbedUnimplementedDepositHandlerServer()
}

// UnimplementedDepositHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepositHandlerServer struct{}

func (UnimplementedDepositHandlerServer) Execute(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDepositHandlerServer) mustEmbedUnimplementedDepositHandlerServer() {}
func (UnimplementedDepositHandlerServer) testEmbeddedByValue()                        {}

// UnsafeDepositHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositHandlerServer will
// result in compilation errors.
type UnsafeDepositHandlerServer interface {
	mustEmbedUnimplementedDepositHandlerServer()
}

func RegisterDepositHandlerServer(s grpc.ServiceRegistrar, srv DepositHandlerServer) {
	// If the following call pancis, it indicates UnimplementedDepositHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepositHandler_ServiceDesc, srv)
}

func _DepositHandler_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositHandlerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositHandler_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositHandlerServer).Execute(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositHandler_ServiceDesc is the grpc.ServiceDesc for DepositHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DepositHandler",
	HandlerType: (*DepositHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DepositHandler_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exchange/deposit/deposit.proto",
}
