// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/exchange/deposit/deposit.proto

package deposit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    string                 `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_proto_exchange_deposit_deposit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_deposit_deposit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_deposit_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *DepositRequest) GetExchangeId() string {
	if x != nil {
		return x.ExchangeId
	}
	return ""
}

func (x *DepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DepositRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_proto_exchange_deposit_deposit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_deposit_deposit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_deposit_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *DepositResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DepositResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_exchange_deposit_deposit_proto protoreflect.FileDescriptor

const file_proto_exchange_deposit_deposit_proto_rawDesc = "" +
	"\n" +
	"$proto/exchange/deposit/deposit.proto\"h\n" +
	"\x0eDepositRequest\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\tR\n" +
	"exchangeId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"J\n" +
	"\x0fDepositResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2>\n" +
	"\x0eDepositHandler\x12,\n" +
	"\aExecute\x12\x0f.DepositRequest\x1a\x10.DepositResponseB0Z.github.com/joseMarciano/crypto-manager/depositb\x06proto3"

var (
	file_proto_exchange_deposit_deposit_proto_rawDescOnce sync.Once
	file_proto_exchange_deposit_deposit_proto_rawDescData []byte
)

func file_proto_exchange_deposit_deposit_proto_rawDescGZIP() []byte {
	file_proto_exchange_deposit_deposit_proto_rawDescOnce.Do(func() {
		file_proto_exchange_deposit_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_deposit_deposit_proto_rawDesc), len(file_proto_exchange_deposit_deposit_proto_rawDesc)))
	})
	return file_proto_exchange_deposit_deposit_proto_rawDescData
}

var file_proto_exchange_deposit_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_deposit_deposit_proto_goTypes = []any{
	(*DepositRequest)(nil),  // 0: DepositRequest
	(*DepositResponse)(nil), // 1: DepositResponse
}
var file_proto_exchange_deposit_deposit_proto_depIdxs = []int32{
	0, // 0: DepositHandler.Execute:input_type -> DepositRequest
	1, // 1: DepositHandler.Execute:output_type -> DepositResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_deposit_deposit_proto_init() }
func file_proto_exchange_deposit_deposit_proto_init() {
	if File_proto_exchange_deposit_deposit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_deposit_deposit_proto_rawDesc), len(file_proto_exchange_deposit_deposit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_deposit_deposit_proto_goTypes,
		DependencyIndexes: file_proto_exchange_deposit_deposit_proto_depIdxs,
		MessageInfos:      file_proto_exchange_deposit_deposit_proto_msgTypes,
	}.Build()
	File_proto_exchange_deposit_deposit_proto = out.File
	file_proto_exchange_deposit_deposit_proto_goTypes = nil
	file_proto_exchange_deposit_deposit_proto_depIdxs = nil
}
